/* SPDX-License-Identifier: AGPL-3.0-only */
import type { MigrationInterface, QueryRunner } from "typeorm";
import { Snowflake } from "../../../util/util/Snowflake";

const schema = [
    'CREATE TABLE IF NOT EXISTS "activity_instance_participants" ("instance_id" int8 NOT NULL, "user_id" int8 NOT NULL, "session_id" varchar NOT NULL, "nonce" varchar, "joined_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), CONSTRAINT "FK_activity_instance_participant_instance_id" FOREIGN KEY ("instance_id") REFERENCES "activity_instances" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_activity_instance_participant_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("instance_id", "user_id"))',
    'CREATE TABLE IF NOT EXISTS "activity_instances" ("id" int8 PRIMARY KEY NOT NULL, "application_id" int8 NOT NULL, "channel_id" int8 NOT NULL, "guild_id" int8, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), CONSTRAINT "UQ_activity_instance_application_channel" UNIQUE ("application_id", "channel_id"), CONSTRAINT "FK_activity_instance_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_activity_instance_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "announcement_deliveries" ("announcement_id" int8 NOT NULL, "user_id" int8 NOT NULL, "status" varchar NOT NULL DEFAULT (\'queued\'), "attempts" integer NOT NULL DEFAULT (0), "next_retry_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), "last_error" varchar, "lease_token" varchar, "message_id" int8, CONSTRAINT "FK_announcement_deliveries_announcement" FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_announcement_deliveries_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("announcement_id", "user_id"))',
    'CREATE TABLE IF NOT EXISTS "announcement_messages" ("message_id" int8 PRIMARY KEY NOT NULL, "channel_id" int8 NOT NULL, "announcement_id" int8 NOT NULL, CONSTRAINT "FK_announcement_messages_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_announcement_messages_announcement_id" FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "announcements" ("id" int8 PRIMARY KEY NOT NULL, "title" varchar, "body" text NOT NULL, "audience" varchar NOT NULL, "sent_by" int8, "recipient_count" integer NOT NULL DEFAULT (0), "attachment_count" integer NOT NULL DEFAULT (0), "durable" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))))',
    'CREATE TABLE IF NOT EXISTS "application_authorizations" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "application_id" int8 NOT NULL, "scopes" text NOT NULL DEFAULT (\'[]\'), "integration_type" integer NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), CONSTRAINT "UQ_application_authorization_user_application" UNIQUE ("user_id", "application_id"), CONSTRAINT "FK_application_authorization_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_application_authorization_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "application_command_permissions" ("id" bigint NOT NULL, "guild_id" int8 NOT NULL, "application_id" int8 NOT NULL, "permissions" text NOT NULL DEFAULT (\'[]\'), CONSTRAINT "FK_application_command_permission_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_application_command_permission_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("id", "guild_id"))',
    'CREATE TABLE IF NOT EXISTS "application_commands" ("id" int8 PRIMARY KEY NOT NULL, "type" integer NOT NULL DEFAULT (1), "application_id" int8 NOT NULL, "guild_id" int8, "name" varchar NOT NULL, "name_localizations" text, "description" varchar NOT NULL, "description_localizations" text, "options" text NOT NULL DEFAULT (\'[]\'), "default_member_permissions" varchar, "dm_permission" boolean NOT NULL DEFAULT (1), "permissions" text, "nsfw" boolean NOT NULL DEFAULT (0), "integration_types" text, "global_popularity_rank" integer NOT NULL DEFAULT (0), "contexts" text, "version" int8 NOT NULL DEFAULT (0), "handler" integer NOT NULL DEFAULT (0))',
    'CREATE TABLE IF NOT EXISTS "application_identities" ("application_id" int8 NOT NULL, "user_id" int8 NOT NULL, "username" varchar, "data" text NOT NULL DEFAULT (\'{}\'), "updated_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), CONSTRAINT "FK_application_identity_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_application_identity_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("application_id", "user_id"))',
    'CREATE TABLE IF NOT EXISTS "application_testers" ("application_id" int8 NOT NULL, "user_id" int8 NOT NULL, "state" integer NOT NULL DEFAULT (2), "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), CONSTRAINT "FK_application_tester_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_application_tester_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("application_id", "user_id"))',
    'CREATE TABLE IF NOT EXISTS "applications" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "icon" varchar, "description" varchar, "summary" varchar, "type" text, "hook" boolean NOT NULL, "bot_public" boolean NOT NULL, "bot_require_code_grant" boolean NOT NULL, "verify_key" varchar NOT NULL, "interactions_private_key" text, "client_secret_hash" varchar, "owner_id" int8 NOT NULL, "flags" integer NOT NULL, "redirect_uris" text, "rpc_application_state" integer, "store_application_state" integer, "verification_state" integer, "interactions_endpoint_url" varchar, "integration_public" boolean, "integration_require_code_grant" boolean, "discoverability_state" integer, "discovery_eligibility_flags" integer, "tags" text, "cover_image" varchar, "install_params" text, "integration_types_config" text, "terms_of_service_url" varchar, "privacy_policy_url" varchar, "guild_id" int8, "custom_install_url" varchar, "assets" text NOT NULL DEFAULT (\'[]\'), "widget_config" text, "widget_public" boolean NOT NULL DEFAULT (0), "bot_user_id" int8, "team_id" int8, CONSTRAINT "REL_2ce5a55796fe4c2f77ece57a64" UNIQUE ("bot_user_id"), CONSTRAINT "FK_application_owner_id" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_application_bot_user_id" FOREIGN KEY ("bot_user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_application_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_application_team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "attachments" ("id" int8 PRIMARY KEY NOT NULL, "filename" varchar NOT NULL, "size" integer NOT NULL, "height" integer, "width" integer, "content_type" varchar, "message_id" int8, "channel_id" int8, "description" varchar, "flags" int2, "content_scan_version" int2, "placeholder_version" int2, "placeholder" varchar, "duration_secs" double precision, "waveform" varchar, "title" varchar, "clip_created_at" datetime, CONSTRAINT "FK_attachment_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_attachment_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "audit_logs" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" varchar, "target_id" bigint, "user_id" int8, "action_type" integer NOT NULL, "options" text, "changes" text NOT NULL, "reason" varchar, CONSTRAINT "FK_audit_log_source_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "automod_rules" ("id" int8 PRIMARY KEY NOT NULL, "creator_id" int8, "enabled" boolean NOT NULL, "event_type" integer NOT NULL, "exempt_channels" text NOT NULL, "exempt_roles" text NOT NULL, "guild_id" int8 NOT NULL, "name" varchar NOT NULL, "position" integer NOT NULL, "trigger_type" integer NOT NULL, "trigger_metadata" text, "actions" text NOT NULL, CONSTRAINT "FK_automod_rule_creator_id" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "avatar_decorations" ("id" int8 PRIMARY KEY NOT NULL, "asset" varchar NOT NULL, "approved" boolean NOT NULL DEFAULT (0), "uploader_id" int8, "public" boolean NOT NULL DEFAULT (0), "allowed_user_ids" text NOT NULL, "allowed_guild_ids" text NOT NULL, "allowed_role_ids" text NOT NULL, CONSTRAINT "FK_avatar_decoration_uploader_id" FOREIGN KEY ("uploader_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "backup_codes" ("id" int8 PRIMARY KEY NOT NULL, "code" varchar NOT NULL, "consumed" boolean NOT NULL, "expired" boolean NOT NULL, "user_id" int8, CONSTRAINT "FK_backup_code_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "badges" ("id" varchar PRIMARY KEY NOT NULL, "description" varchar NOT NULL, "icon" varchar NOT NULL, "link" varchar)',
    'CREATE TABLE IF NOT EXISTS "bans" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8, "guild_id" int8, "executor_id" int8, "ip" varchar, "reason" varchar, CONSTRAINT "FK_ban_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_ban_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_ban_executor_id" FOREIGN KEY ("executor_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "categories" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "localizations" text NOT NULL, "is_primary" boolean, "icon" varchar)',
    'CREATE TABLE IF NOT EXISTS "channels" ("id" int8 PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "name" varchar, "version" bigint NOT NULL DEFAULT (0), "icon" text, "type" integer NOT NULL, "last_message_id" int8, "guild_id" int8, "parent_id" int8, "owner_id" int8, "last_pin_timestamp" datetime, "default_auto_archive_duration" integer, "permission_overwrites" text, "video_quality_mode" integer, "bitrate" integer, "user_limit" integer, "nsfw" boolean NOT NULL, "rate_limit_per_user" integer, "topic" varchar, "retention_policy_id" varchar, "flags" integer NOT NULL, "default_thread_rate_limit_per_user" integer, "thread_metadata" text, "member_count" integer, "message_count" integer, "total_message_sent" integer, "applied_tags" text, "status" text, "e2ee_enabled_at" datetime, "default_reaction_emoji" text, "default_sort_order" integer, "default_forum_layout" integer, "default_tag_setting" varchar, CONSTRAINT "FK_channel_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_channel_parent_id" FOREIGN KEY ("parent_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_channel_owner_id" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "client_release" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "pub_date" datetime NOT NULL, "url" varchar NOT NULL, "platform" varchar NOT NULL, "enabled" boolean NOT NULL, "notes" varchar)',
    'CREATE TABLE IF NOT EXISTS "cloud_attachments" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8, "channel_id" int8, "upload_filename" varchar NOT NULL, "user_attachment_id" varchar, "user_filename" varchar NOT NULL, "user_file_size" integer, "user_original_content_type" varchar, "user_is_clip" boolean, "size" integer, "height" integer, "width" integer, "content_type" varchar, CONSTRAINT "FK_cloud_attachment_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_cloud_attachment_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "collectible_purchases" ("user_id" int8 NOT NULL, "sku_id" int8 NOT NULL, "purchased_at" datetime NOT NULL, CONSTRAINT "FK_collectible_purchase_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("user_id", "sku_id"))',
    'CREATE TABLE IF NOT EXISTS "config" ("key" varchar PRIMARY KEY NOT NULL, "value" text)',
    'CREATE TABLE IF NOT EXISTS "connected_accounts" ("id" int8 PRIMARY KEY NOT NULL, "external_id" varchar NOT NULL, "user_id" int8, "friend_sync" boolean NOT NULL, "name" varchar NOT NULL, "revoked" boolean NOT NULL, "show_activity" integer NOT NULL, "type" varchar NOT NULL, "verified" boolean NOT NULL, "visibility" integer NOT NULL, "integrations" text NOT NULL, "metadata" text, "metadata_visibility" integer NOT NULL, "two_way_link" boolean NOT NULL, "token_data" text, CONSTRAINT "FK_connected_account_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "connection_config" ("key" varchar PRIMARY KEY NOT NULL, "value" text)',
    'CREATE TABLE IF NOT EXISTS "custom_games" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "aliases" text NOT NULL DEFAULT (\'[]\'), "icon_hash" varchar, "cover_image_hash" varchar, "created_by" int8, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))))',
    'CREATE TABLE IF NOT EXISTS "e2ee_backup_keys" ("user_id" int8 NOT NULL, "message_id" int8 NOT NULL, "enc" varchar NOT NULL, "wrapped" varchar NOT NULL, "created_at" datetime NOT NULL, CONSTRAINT "FK_e2ee_backup_key_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("user_id", "message_id"))',
    'CREATE TABLE IF NOT EXISTS "e2ee_devices" ("id" varchar PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "signing_key" varchar NOT NULL, "identity_signature" varchar, "status" varchar NOT NULL, "name" varchar, "prekey_id" integer NOT NULL, "prekey_public" varchar NOT NULL, "prekey_signature" varchar NOT NULL, "prekey_updated_at" datetime NOT NULL, "created_at" datetime NOT NULL, "revoked_at" datetime, "session_id" varchar, CONSTRAINT "FK_e2ee_device_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "e2ee_identities" ("user_id" int8 PRIMARY KEY NOT NULL, "public_key" varchar NOT NULL, "previous_key" varchar, "rotation_signature" varchar, "created_at" datetime NOT NULL, CONSTRAINT "FK_e2ee_identity_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "e2ee_key_backups" ("user_id" int8 PRIMARY KEY NOT NULL, "version" integer NOT NULL, "mode" varchar NOT NULL, "kdf" text NOT NULL, "salt" varchar NOT NULL, "wrapped_secret" varchar, "identity_key" varchar NOT NULL, "wrapped_identity" varchar NOT NULL, "backup_public_key" varchar NOT NULL, "backup_key_signature" varchar NOT NULL, "wrapped_backup_key" varchar NOT NULL, "updated_at" datetime NOT NULL, "trust" varchar, "trust_version" integer NOT NULL DEFAULT (0), CONSTRAINT "FK_e2ee_key_backup_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "e2ee_recovery" ("user_id" int8 PRIMARY KEY NOT NULL, "identity_key" varchar NOT NULL, "backup_public_key" varchar NOT NULL, "backup_version" integer NOT NULL, "encrypted_secret" varchar NOT NULL, "updated_at" datetime NOT NULL, CONSTRAINT "FK_e2ee_recovery_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "embed_cache" ("id" int8 PRIMARY KEY NOT NULL, "url" varchar NOT NULL, "embed" text, "embeds" text, "created_at" datetime NOT NULL DEFAULT (datetime(\'now\')))',
    'CREATE TABLE IF NOT EXISTS "embedded_activities" ("application_id" int8 PRIMARY KEY NOT NULL, "builtin" varchar, "url_mappings" text NOT NULL DEFAULT (\'[]\'), "config" text NOT NULL DEFAULT (\'{}\'), "assets" text NOT NULL DEFAULT (\'[]\'), "shelf_rank" integer NOT NULL DEFAULT (0), "on_shelf" boolean NOT NULL DEFAULT (1), CONSTRAINT "UQ_ce7d7eadc20540d25d10fe0deab" UNIQUE ("builtin"), CONSTRAINT "FK_embedded_activity_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "emojis" ("id" int8 PRIMARY KEY NOT NULL, "animated" boolean NOT NULL, "available" boolean NOT NULL, "guild_id" int8, "application_id" int8, "user_id" int8, "managed" boolean NOT NULL, "name" varchar NOT NULL, "version" bigint NOT NULL DEFAULT (0), "require_colons" boolean NOT NULL, "roles" text NOT NULL, "groups" text, CONSTRAINT "FK_emoji_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_emoji_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_emoji_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "guild_join_requests" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" int8 NOT NULL, "user_id" int8 NOT NULL, "application_status" varchar NOT NULL DEFAULT (\'STARTED\'), "form_responses" text NOT NULL DEFAULT (\'[]\'), "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), "actioned_at" datetime, "actioned_by_id" int8, "rejection_reason" text, "last_seen" datetime, "interview_channel_id" int8, CONSTRAINT "FK_guild_join_requests_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_guild_join_requests_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_guild_join_requests_actioned_by_id" FOREIGN KEY ("actioned_by_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "guild_scheduled_event_users" ("id" int8 PRIMARY KEY NOT NULL, "guild_scheduled_event_id" int8 NOT NULL, "user_id" int8 NOT NULL, "guild_id" int8 NOT NULL, "guild_scheduled_event_exception_id" int8, "response" integer NOT NULL DEFAULT (1), CONSTRAINT "FK_guild_scheduled_event_user_event_id" FOREIGN KEY ("guild_scheduled_event_id") REFERENCES "guild_scheduled_events" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_guild_scheduled_event_user_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "guild_scheduled_events" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" int8 NOT NULL, "channel_id" int8, "creator_id" int8, "name" varchar NOT NULL, "description" text, "scheduled_start_time" datetime NOT NULL, "scheduled_end_time" datetime, "privacy_level" integer NOT NULL DEFAULT (2), "status" integer NOT NULL DEFAULT (1), "entity_type" integer NOT NULL, "entity_id" int8, "entity_metadata" text, "image" varchar, "recurrence_rule" text, "exceptions" text NOT NULL DEFAULT (\'[]\'), "auto_start" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_guild_scheduled_event_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_guild_scheduled_event_creator_id" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "guilds" ("id" int8 PRIMARY KEY NOT NULL, "afk_channel_id" int8, "afk_timeout" integer, "banner" varchar, "default_message_notifications" integer, "description" varchar, "discovery_splash" varchar, "explicit_content_filter" integer, "safety_alerts_channel_id" int8, "features" text NOT NULL, "primary_category_id" int2, "icon" varchar, "large" boolean NOT NULL, "max_members" integer, "max_presences" integer, "max_video_channel_users" integer, "member_count" integer, "presence_count" integer, "template_id" int8, "mfa_level" integer, "name" varchar NOT NULL, "owner_id" int8, "preferred_locale" varchar, "premium_subscription_count" integer, "premium_tier" integer NOT NULL, "public_updates_channel_id" int8, "rules_channel_id" int8, "region" varchar, "splash" varchar, "system_channel_id" int8, "system_channel_flags" integer, "unavailable" boolean NOT NULL, "verification_level" integer, "welcome_screen" text NOT NULL, "widget_channel_id" int8, "widget_enabled" boolean NOT NULL, "nsfw_level" integer, "nsfw" boolean NOT NULL, "parent" varchar, "premium_progress_bar_enabled" boolean, "channel_ordering" text NOT NULL, "channels_version" bigint NOT NULL DEFAULT (0), "discovery_weight" integer NOT NULL DEFAULT (0), "discovery_excluded" boolean NOT NULL DEFAULT (0), "vanity_url_code" varchar, "profile" text, "home_settings" text, "onboarding" text, "member_verification" text, "discovery_metadata" text, "incidents_data" text, CONSTRAINT "FK_guild_afk_channel_id" FOREIGN KEY ("afk_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_guild_template_id" FOREIGN KEY ("template_id") REFERENCES "templates" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_guild_owner_id" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_guild_public_updates_channel_id" FOREIGN KEY ("public_updates_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_guild_rules_channel_id" FOREIGN KEY ("rules_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_guild_system_channel_id" FOREIGN KEY ("system_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_guild_widget_channel_id" FOREIGN KEY ("widget_channel_id") REFERENCES "channels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "instance_bans" ("id" int8 PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime(\'now\')), "reason" varchar NOT NULL, "user_id" int8, "fingerprint" varchar, "ip_address" varchar, "is_allowlisted" boolean NOT NULL DEFAULT (0), "is_from_other_instance_ban" boolean NOT NULL DEFAULT (0), "origin_instance_ban_id" int8, CONSTRAINT "REL_0b02d18d0d830f160c921192a3" UNIQUE ("origin_instance_ban_id"), CONSTRAINT "FK_origin_instance_ban_id" FOREIGN KEY ("origin_instance_ban_id") REFERENCES "instance_bans" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "invites" ("code" varchar PRIMARY KEY NOT NULL, "temporary" boolean NOT NULL, "uses" integer NOT NULL, "max_uses" integer NOT NULL, "max_age" integer NOT NULL, "created_at" datetime NOT NULL, "expires_at" datetime, "guild_id" int8, "channel_id" int8, "inviter_id" int8, "target_user_id" int8, "target_user_type" integer, "vanity_url" boolean, "flags" integer NOT NULL, CONSTRAINT "FK_invite_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_invite_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_invite_inviter_id" FOREIGN KEY ("inviter_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_invite_target_user_id" FOREIGN KEY ("target_user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "member_roles" ("index" integer NOT NULL, "role_id" int8 NOT NULL, CONSTRAINT "FK_member_role_member_index" FOREIGN KEY ("index") REFERENCES "members" ("index") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_member_role_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("index", "role_id"))',
    'CREATE TABLE IF NOT EXISTS "members" ("index" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "id" int8 NOT NULL, "guild_id" int8 NOT NULL, "nick" varchar, "joined_at" datetime NOT NULL, "premium_since" bigint, "deaf" boolean NOT NULL, "mute" boolean NOT NULL, "pending" boolean NOT NULL, "source_invite_code" varchar, "join_source_type" integer, "inviter_id" bigint, "onboarding_responses" text, "settings" text NOT NULL, "last_message_id" int8, "joined_by" varchar, "avatar" varchar, "banner" varchar, "bio" varchar NOT NULL, "theme_colors" text, "pronouns" varchar, "communication_disabled_until" datetime, "unusual_dm_activity_until" datetime, "avatar_decoration_data" text, "display_name_styles" text, "collectibles" text, "profile_collectibles" text, "flags" integer NOT NULL DEFAULT (0), CONSTRAINT "FK_member_user_id" FOREIGN KEY ("id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_member_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "mention_dismissals" ("user_id" int8 NOT NULL, "message_id" int8 NOT NULL, CONSTRAINT "FK_mention_dismissal_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_mention_dismissal_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("user_id", "message_id"))',
    'CREATE TABLE IF NOT EXISTS "message_channel_mentions" ("message_id" int8 NOT NULL, "channel_id" int8 NOT NULL, CONSTRAINT "FK_message_channel_mentions_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_message_channel_mentions_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("message_id", "channel_id"))',
    'CREATE TABLE IF NOT EXISTS "message_role_mentions" ("message_id" int8 NOT NULL, "role_id" int8 NOT NULL, CONSTRAINT "FK_message_role_mentions_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_message_role_mentions_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("message_id", "role_id"))',
    'CREATE TABLE IF NOT EXISTS "message_stickers" ("message_id" int8 NOT NULL, "sticker_id" int8 NOT NULL, CONSTRAINT "FK_message_stickers_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_message_stickers_sticker_id" FOREIGN KEY ("sticker_id") REFERENCES "stickers" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("message_id", "sticker_id"))',
    'CREATE TABLE IF NOT EXISTS "message_user_mentions" ("message_id" int8 NOT NULL, "user_id" int8 NOT NULL, CONSTRAINT "FK_message_mentions_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_message_mentions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("message_id", "user_id"))',
    'CREATE TABLE IF NOT EXISTS "messages" ("id" int8 PRIMARY KEY NOT NULL, "channel_id" int8, "thread_id" int8, "guild_id" int8, "author_id" int8, "member_id" int8, "webhook_id" int8, "application_id" int8, "content" varchar, "timestamp" datetime NOT NULL DEFAULT (datetime(\'now\')), "edited_timestamp" datetime, "tts" boolean, "mention_everyone" boolean, "embeds" text NOT NULL, "reactions" text NOT NULL, "nonce" text, "pinned_at" datetime, "type" integer NOT NULL, "activity" text, "flags" integer NOT NULL DEFAULT (0), "message_reference" text, "interaction" text, "interaction_metadata" text, "components" text, "poll" text, "username" varchar, "avatar" varchar, "message_snapshots" text NOT NULL DEFAULT (\'[]\'), "encrypted" text, "soundboard_sounds" text, "call" text, "message_reference_id" int8, CONSTRAINT "FK_message_thread_id" FOREIGN KEY ("thread_id") REFERENCES "channels" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_message_author_id" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_message_member_id" FOREIGN KEY ("member_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_message_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_message_message_reference_id" FOREIGN KEY ("message_reference_id") REFERENCES "messages" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "migrations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "timestamp" bigint NOT NULL, "name" varchar NOT NULL)',
    'CREATE TABLE IF NOT EXISTS "notes" ("id" int8 PRIMARY KEY NOT NULL, "content" varchar NOT NULL, "owner_id" int8, "target_id" int8, CONSTRAINT "UQ_74e6689b9568cc965b8bfc9150b" UNIQUE ("owner_id", "target_id"), CONSTRAINT "FK_note_owner_id" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_note_target_id" FOREIGN KEY ("target_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "oauth2_tokens" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "application_id" int8 NOT NULL, "authorization_id" int8, "scopes" text NOT NULL DEFAULT (\'[]\'), "access_token_hash" varchar NOT NULL, "refresh_token_hash" varchar, "code_hash" varchar, "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), CONSTRAINT "FK_oauth2_token_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_oauth2_token_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_oauth2_token_authorization_id" FOREIGN KEY ("authorization_id") REFERENCES "application_authorizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "push_devices" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "session_id" varchar, "provider" varchar NOT NULL, "token" text NOT NULL, "keys" text, "voip_provider" varchar, "voip_token" text, "created_at" datetime NOT NULL DEFAULT (datetime(\'now\')), CONSTRAINT "FK_push_device_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_push_device_session_id" FOREIGN KEY ("session_id") REFERENCES "sessions" ("session_id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "rate_limits" ("id" varchar PRIMARY KEY NOT NULL, "executor_id" varchar NOT NULL, "hits" integer NOT NULL, "blocked" boolean NOT NULL, "expires_at" datetime NOT NULL)',
    'CREATE TABLE IF NOT EXISTS "read_states" ("id" int8 PRIMARY KEY NOT NULL, "channel_id" int8 NOT NULL, "user_id" int8 NOT NULL, "last_message_id" int8, "last_acked_id" int8, "notifications_cursor" varchar, "mention_count" integer NOT NULL DEFAULT (0), "badge_count" integer NOT NULL DEFAULT (0), "last_pin_timestamp" datetime, "read_state_type" integer NOT NULL DEFAULT (0), "flags" integer NOT NULL DEFAULT (0), CONSTRAINT "FK_read_state_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_read_state_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "recipients" ("id" int8 PRIMARY KEY NOT NULL, "channel_id" int8 NOT NULL, "user_id" int8 NOT NULL, "closed" boolean NOT NULL DEFAULT (0), "message_request_timestamp" datetime, CONSTRAINT "FK_recipient_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_recipient_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "relationships" ("id" int8 PRIMARY KEY NOT NULL, "from_id" int8 NOT NULL, "to_id" int8 NOT NULL, "nickname" varchar, "type" integer NOT NULL, "user_ignored" boolean NOT NULL DEFAULT (0), "note" varchar, "stranger_request" boolean, "is_spam_request" boolean, "since" datetime, CONSTRAINT "FK_relationship_from_id" FOREIGN KEY ("from_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_relationship_to_id" FOREIGN KEY ("to_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "report_menus" ("id" int8 PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "variant" varchar NOT NULL, "isCurrent" boolean NOT NULL, "inherits" varchar, "content" jsonb NOT NULL)',
    'CREATE TABLE IF NOT EXISTS "reports" ("id" int8 PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "status" varchar NOT NULL DEFAULT (\'open\'), "reporter_id" int8, "reported_user_id" int8, "guild_id" int8, "channel_id" int8, "message_id" int8, "application_id" int8, "stage_instance_id" int8, "guild_scheduled_event_id" int8, "widget_id" varchar, "reason" text NOT NULL DEFAULT (\'\'), "breadcrumbs" text NOT NULL DEFAULT (\'[]\'), "elements" text NOT NULL DEFAULT (\'{}\'), "snapshot" text, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), "resolved_by" int8, "resolved_at" datetime, "resolution_note" text, "violation_id" int8)',
    'CREATE TABLE IF NOT EXISTS "roles" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" int8 NOT NULL, "color" integer NOT NULL, "hoist" boolean NOT NULL, "managed" boolean NOT NULL DEFAULT (0), "mentionable" boolean NOT NULL, "name" varchar NOT NULL, "permissions" varchar NOT NULL, "position" integer NOT NULL, "icon" varchar, "unicode_emoji" varchar, "tags" text, "flags" integer NOT NULL DEFAULT (0), "version" bigint NOT NULL DEFAULT (0), "colors" text NOT NULL, CONSTRAINT "FK_role_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "saved_messages" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "channel_id" int8 NOT NULL, "message_id" int8 NOT NULL, "saved_at" datetime NOT NULL DEFAULT (strftime(\'%Y-%m-%d %H:%M:%f\', \'now\')), "due_at" datetime, "notes" varchar, CONSTRAINT "UQ_saved_message_user_message" UNIQUE ("user_id", "message_id"), CONSTRAINT "FK_saved_message_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_saved_message_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_saved_message_message_id" FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "scheduled_messages" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "channel_id" int8 NOT NULL, "send_at" datetime NOT NULL, "payload" text NOT NULL, "state" int2 NOT NULL DEFAULT (0), "claim_token" varchar, "claim_until" datetime, CONSTRAINT "FK_scheduled_message_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_scheduled_message_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "security_keys" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8, "key_id" varchar NOT NULL, "public_key" varchar NOT NULL, "counter" integer NOT NULL, "name" varchar NOT NULL, CONSTRAINT "FK_security_key_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "security_settings" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" int8, "channel_id" int8, "encryption_permission_mask" integer NOT NULL, "allowed_algorithms" text NOT NULL, "current_algorithm" varchar NOT NULL, "used_since_message" varchar)',
    'CREATE TABLE IF NOT EXISTS "sessions" ("session_id" varchar PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "activities" text NOT NULL DEFAULT (\'[]\'), "client_info" text NOT NULL, "client_status" text NOT NULL, "status" varchar NOT NULL, "is_admin_session" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime(\'now\')), "last_seen" datetime, "last_seen_ip" varchar, "last_seen_location" varchar, "last_seen_location_info" text, "session_nickname" varchar, CONSTRAINT "FK_session_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "soundboard_sounds" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" int8 NOT NULL, "name" varchar NOT NULL, "volume" double precision NOT NULL DEFAULT (1), "emoji_id" int8, "emoji_name" varchar, "user_id" int8, "available" boolean NOT NULL DEFAULT (1), CONSTRAINT "FK_soundboard_sound_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_soundboard_sound_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "stage_instances" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" int8 NOT NULL, "channel_id" int8 NOT NULL, "topic" varchar NOT NULL, "privacy_level" integer NOT NULL DEFAULT (2), "guild_scheduled_event_id" int8, CONSTRAINT "UQ_fea34641fc99d63575d946dcd0d" UNIQUE ("channel_id"), CONSTRAINT "FK_stage_instance_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_stage_instance_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "status_components" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" text, "status" varchar NOT NULL DEFAULT (\'operational\'), "position" integer NOT NULL DEFAULT (0), "updated_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))))',
    'CREATE TABLE IF NOT EXISTS "status_incidents" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "impact" varchar NOT NULL DEFAULT (\'none\'), "status" varchar NOT NULL DEFAULT (\'investigating\'), "updates" text NOT NULL DEFAULT (\'[]\'), "component_ids" text NOT NULL DEFAULT (\'[]\'), "scheduled_for" datetime, "scheduled_until" datetime, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), "updated_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), "resolved_at" datetime)',
    'CREATE TABLE IF NOT EXISTS "sticker_packs" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar, "banner_asset_id" varchar, "sku_id" int8, "cover_sticker_id" varchar, "coverStickerId" int8, CONSTRAINT "FK_sticker_pack_cover_sticker_id" FOREIGN KEY ("coverStickerId") REFERENCES "stickers" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "stickers" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "version" bigint NOT NULL DEFAULT (0), "description" varchar, "available" boolean, "tags" varchar, "pack_id" int8, "guild_id" int8, "user_id" int8, "type" integer NOT NULL, "format_type" integer NOT NULL, "sort_value" integer, CONSTRAINT "FK_sticker_pack_id" FOREIGN KEY ("pack_id") REFERENCES "sticker_packs" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_sticker_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_sticker_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "storage_inventory_runs" ("namespace" varchar PRIMARY KEY NOT NULL, "epoch" varchar NOT NULL, "root_identity" varchar NOT NULL, "barrier_digest" varchar NOT NULL, "state" varchar NOT NULL DEFAULT (\'running\'), "phase" varchar NOT NULL DEFAULT (\'content\'), "error_code" varchar, "policy" text NOT NULL, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), "completed_at" datetime)',
    'CREATE TABLE IF NOT EXISTS "storage_inventory_work" ("namespace" varchar NOT NULL, "kind" varchar NOT NULL, "path" varchar NOT NULL, "epoch" varchar NOT NULL, "identity" varchar NOT NULL, "cursor" bigint NOT NULL DEFAULT (\'0\'), "prefix" varchar NOT NULL, "state" varchar NOT NULL DEFAULT (\'pending\'), PRIMARY KEY ("namespace", "kind", "path"))',
    'CREATE TABLE IF NOT EXISTS "storage_quota_accounts" ("namespace" varchar NOT NULL, "key" varchar NOT NULL, "used_bytes" bigint NOT NULL DEFAULT (\'0\'), "reserved_bytes" bigint NOT NULL DEFAULT (\'0\'), "used_objects" bigint NOT NULL DEFAULT (\'0\'), "reserved_objects" bigint NOT NULL DEFAULT (\'0\'), "state" varchar NOT NULL DEFAULT (\'inventory-required\'), PRIMARY KEY ("namespace", "key"))',
    'CREATE TABLE IF NOT EXISTS "storage_quota_objects" ("namespace" varchar NOT NULL, "path" varchar NOT NULL, "principal" varchar NOT NULL, "category" varchar NOT NULL, "bytes" bigint NOT NULL DEFAULT (\'0\'), "generation" varchar NOT NULL, "pending_operation" varchar, "state" varchar NOT NULL DEFAULT (\'reserved\'), PRIMARY KEY ("namespace", "path"))',
    'CREATE TABLE IF NOT EXISTS "storage_quota_operations" ("namespace" varchar NOT NULL, "id" varchar NOT NULL, "path" varchar NOT NULL, "principal" varchar NOT NULL, "category" varchar NOT NULL, "upper_bytes" bigint NOT NULL, "prior_bytes" bigint NOT NULL, "prior_exists" boolean NOT NULL, "prior_generation" varchar NOT NULL, "state" varchar NOT NULL DEFAULT (\'reserved\'), "actual_bytes" bigint, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), PRIMARY KEY ("namespace", "id"))',
    'CREATE TABLE IF NOT EXISTS "store_hidden_packs" ("sku_id" int8 PRIMARY KEY NOT NULL, "hidden" boolean NOT NULL DEFAULT (1), "customization" text NOT NULL DEFAULT (\'{}\'))',
    'CREATE TABLE IF NOT EXISTS "store_items" ("id" int8 PRIMARY KEY NOT NULL, "pack_id" int8 NOT NULL, "type" integer NOT NULL, "name" varchar NOT NULL, "summary" text NOT NULL DEFAULT (\'\'), "label" text NOT NULL DEFAULT (\'\'), "data" text NOT NULL DEFAULT (\'{}\'), "position" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), CONSTRAINT "FK_store_items_pack_id" FOREIGN KEY ("pack_id") REFERENCES "store_packs" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "store_packs" ("id" int8 PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "summary" text NOT NULL DEFAULT (\'\'), "banner_hash" varchar, "logo_hash" varchar, "position" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))))',
    'CREATE TABLE IF NOT EXISTS "stream_sessions" ("id" int8 PRIMARY KEY NOT NULL, "stream_id" int8 NOT NULL, "user_id" int8 NOT NULL, "token" varchar, "session_id" varchar NOT NULL, "used" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_stream_session_stream_id" FOREIGN KEY ("stream_id") REFERENCES "streams" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_stream_session_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "streams" ("id" int8 PRIMARY KEY NOT NULL, "owner_id" int8 NOT NULL, "channel_id" int8 NOT NULL, "endpoint" varchar NOT NULL, CONSTRAINT "FK_stream_owner_id" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_stream_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "tags" ("id" int8 PRIMARY KEY NOT NULL, "channel_id" int8 NOT NULL, "name" varchar NOT NULL, "moderated" boolean NOT NULL, "emoji_id" int8, "emoji_name" varchar, "position" integer NOT NULL DEFAULT (0), CONSTRAINT "FK_tag_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "team_members" ("id" int8 PRIMARY KEY NOT NULL, "membership_state" integer NOT NULL, "permissions" text NOT NULL, "role" varchar NOT NULL, "team_id" int8, "user_id" int8, CONSTRAINT "FK_team_member_team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_team_member_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "teams" ("id" int8 PRIMARY KEY NOT NULL, "icon" varchar, "name" varchar NOT NULL, "owner_user_id" int8, CONSTRAINT "FK_team_owner_user_id" FOREIGN KEY ("owner_user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "templates" ("id" int8 PRIMARY KEY NOT NULL, "code" varchar NOT NULL, "name" varchar NOT NULL, "description" varchar, "usage_count" integer, "creator_id" int8, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "source_guild_id" int8, "serialized_source_guild" text NOT NULL, CONSTRAINT "UQ_be38737bf339baf63b1daeffb55" UNIQUE ("code"), CONSTRAINT "FK_template_creator_id" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_template_source_guild_id" FOREIGN KEY ("source_guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "thread_members" ("index" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "id" int8 NOT NULL, "member_idx" integer NOT NULL, "user_id" int8, "join_timestamp" datetime NOT NULL, "muted" boolean NOT NULL, "mute_config" text, "flags" integer NOT NULL, CONSTRAINT "FK_thread_member_channel_id" FOREIGN KEY ("id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_thread_member_member_id" FOREIGN KEY ("member_idx") REFERENCES "members" ("index") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "user_settings" ("index" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "afk_timeout" integer, "allow_accessibility_detection" boolean, "animate_emoji" boolean, "animate_stickers" integer, "contact_sync_enabled" boolean, "convert_emoticons" boolean, "custom_status" text, "default_guilds_restricted" boolean, "detect_platform_accounts" boolean, "developer_mode" boolean, "disable_games_tab" boolean, "enable_tts_command" boolean, "explicit_content_filter" integer, "friend_discovery_flags" integer, "friend_source_flags" text, "gateway_connected" boolean, "gif_auto_play" boolean, "guild_folders" text, "guild_positions" text, "inline_attachment_media" boolean, "inline_embed_media" boolean, "locale" varchar, "message_display_compact" boolean, "native_phone_integration_enabled" boolean, "render_embeds" boolean, "render_reactions" boolean, "restricted_guilds" text, "show_current_game" boolean, "status" varchar, "stream_notifications_enabled" boolean, "theme" varchar, "timezone_offset" integer, "view_nsfw_guilds" boolean)',
    'CREATE TABLE IF NOT EXISTS "user_settings_protos" ("user_id" int8 PRIMARY KEY NOT NULL, "userSettings" varchar, "frecencySettings" varchar, CONSTRAINT "FK_user_settings_proto_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "user_violations" ("id" int8 PRIMARY KEY NOT NULL, "user_id" int8 NOT NULL, "classification_type" integer NOT NULL, "description" text NOT NULL, "actions" text NOT NULL DEFAULT (\'[]\'), "flagged_content" text NOT NULL DEFAULT (\'[]\'), "issued_by" int8, "created_at" datetime NOT NULL DEFAULT ((strftime(\'%Y-%m-%d %H:%M:%f\', \'now\'))), "expires_at" datetime NOT NULL, "appeal_status" integer, "appealed_at" datetime, "appeal_signal" integer, "appeal_user_input" text, "appeal_review_messages" text NOT NULL DEFAULT (\'[]\'), "appeal_resolved_by" int8, CONSTRAINT "FK_185c908a50a51e776f3ec3a2267" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "users" ("id" int8 PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "discriminator" varchar NOT NULL, "global_name" varchar, "avatar" varchar, "accent_color" integer, "banner" varchar, "theme_colors" text, "pronouns" varchar, "phone" varchar, "desktop" boolean NOT NULL, "mobile" boolean NOT NULL, "premium" boolean NOT NULL, "premium_type" integer NOT NULL, "bot" boolean NOT NULL, "bio" varchar NOT NULL, "system" boolean NOT NULL, "nsfw_allowed" boolean NOT NULL, "mfa_enabled" boolean NOT NULL, "webauthn_enabled" boolean NOT NULL DEFAULT (0), "totp_secret" varchar, "totp_last_ticket" varchar, "created_at" datetime NOT NULL, "premium_since" datetime, "verified" boolean NOT NULL, "disabled" boolean NOT NULL, "deleted" boolean NOT NULL, "hide_premium_badge" boolean NOT NULL DEFAULT (0), "account_standing" integer, "email" varchar, "flags" bigint NOT NULL, "public_flags" bigint NOT NULL, "purchased_flags" bigint NOT NULL, "premium_usage_flags" integer NOT NULL, "rights" bigint NOT NULL, "data" text NOT NULL, "fingerprints" text NOT NULL, "badge_ids" text, "avatar_decoration_data" text, "display_name_styles" text, "collectibles" text, "primary_guild" text, "profile_collectibles" text, "recent_avatars" text, "account_preferences" text, "private_channel_settings" text, "pride_badges" text NOT NULL DEFAULT (\'[]\'), "profile_widgets" text, "avatar_decoration_id" int8, "settingsIndex" integer, CONSTRAINT "REL_0c14beb78d8c5ccba66072adbc" UNIQUE ("settingsIndex"), CONSTRAINT "REL_119117c066ad70abbe777d34f4" UNIQUE ("avatar_decoration_id"), CONSTRAINT "FK_user_settings_index" FOREIGN KEY ("settingsIndex") REFERENCES "user_settings" ("index") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_user_avatar_decoration_id" FOREIGN KEY ("avatar_decoration_id") REFERENCES "avatar_decorations" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "valid_registration_tokens" ("token" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "expires_at" datetime NOT NULL)',
    'CREATE TABLE IF NOT EXISTS "voice_states" ("id" int8 PRIMARY KEY NOT NULL, "guild_id" int8, "channel_id" int8, "user_id" int8, "session_id" varchar NOT NULL, "token" varchar, "deaf" boolean NOT NULL, "mute" boolean NOT NULL, "self_deaf" boolean NOT NULL, "self_mute" boolean NOT NULL, "self_stream" boolean, "self_video" boolean NOT NULL, "suppress" boolean NOT NULL, "request_to_speak_timestamp" datetime, "connected_at" bigint, CONSTRAINT "FK_voice_state_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_voice_state_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_voice_state_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE TABLE IF NOT EXISTS "webhooks" ("id" int8 PRIMARY KEY NOT NULL, "type" integer NOT NULL, "name" varchar, "avatar" varchar, "token" varchar, "guild_id" int8, "channel_id" int8, "application_id" int8, "user_id" int8, "source_guild_id" int8, "source_channel_id" int8, CONSTRAINT "FK_webhook_guild_id" FOREIGN KEY ("guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_webhook_channel_id" FOREIGN KEY ("channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_webhook_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_webhook_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_webhook_source_guild_id" FOREIGN KEY ("source_guild_id") REFERENCES "guilds" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_webhook_source_channel_id" FOREIGN KEY ("source_channel_id") REFERENCES "channels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
    'CREATE INDEX IF NOT EXISTS "IDX_05535bc695e9f7ee104616459d" ON "messages" ("author_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_085d540d9f418cfbdc7bd55bb1" ON "sessions" ("user_id") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_0abf8b443321bd3cf7f81ee17a" ON "read_states" ("channel_id", "user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_124558309acd065c3cf083b848" ON "soundboard_sounds" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_16395c9069e88c5f93cd658e9a" ON "message_user_mentions" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_2b34e1145cafb79c6c5c193d12" ON "message_stickers" ("sticker_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_30114cbe788f0affbd8b8bf1f1" ON "message_role_mentions" ("message_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_32f530caa79d0e7d295eb59f62" ON "message_channel_mentions" ("channel_id") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_38d4f704373da3f0dc9b352ac9" ON "thread_members" ("id", "member_idx") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_3ed7a60fb7dbe04e1ba9332a8b" ON "messages" ("channel_id", "id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_5d7ddc8a5f9c167f548625e772" ON "member_roles" ("index") ',
    'CREATE INDEX IF NOT EXISTS "IDX_724f8b11056c706429933bdf87" ON "message_stickers" ("message_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_900f52a6d0f53bdcb2e9079017" ON "message_channel_mentions" ("message_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_972e8e013af7698f8aa8bc3fc8" ON "message_user_mentions" ("message_id") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_a0b2ff0a598df0b0d055934a17" ON "relationships" ("from_id", "to_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_activity_instance_participants_user_id" ON "activity_instance_participants" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_activity_instances_channel_id" ON "activity_instances" ("channel_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_activity_instances_guild_id" ON "activity_instances" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_announcement_deliveries_ready" ON "announcement_deliveries" ("status", "next_retry_at") ',
    'CREATE INDEX IF NOT EXISTS "IDX_announcement_messages_announcement_id" ON "announcement_messages" ("announcement_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_application_identities_user_id" ON "application_identities" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_application_testers_user_id" ON "application_testers" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_attachments_message_id" ON "attachments" ("message_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_audit_log_guild_id" ON "audit_logs" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_automod_rules_guild_id" ON "automod_rules" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_avatar_decoration_uploader_id" ON "avatar_decorations" ("uploader_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_bans_guild_user" ON "bans" ("guild_id", "user_id") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_bb2bf9386ac443afbbbf9f12d3" ON "members" ("id", "guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_ce866308ad8ddf9b6abce06b33" ON "message_role_mentions" ("role_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_channels_guild_id" ON "channels" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_channels_parent_id" ON "channels" ("parent_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_connected_accounts_user_id" ON "connected_accounts" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_e2ee_device_user_id" ON "e2ee_devices" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_e9080e7a7997a0170026d5139c" ON "member_roles" ("role_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_emojis_guild_id" ON "emojis" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_guild_join_requests_guild_status" ON "guild_join_requests" ("guild_id", "application_status") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_guild_join_requests_guild_user" ON "guild_join_requests" ("guild_id", "user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_guild_join_requests_user_id" ON "guild_join_requests" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_guild_scheduled_event_users_event_user" ON "guild_scheduled_event_users" ("guild_scheduled_event_id", "user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_guild_scheduled_event_users_user_id" ON "guild_scheduled_event_users" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_guild_scheduled_events_guild_id" ON "guild_scheduled_events" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_instance_ban_fingerprint" ON "instance_bans" ("fingerprint") ',
    'CREATE INDEX IF NOT EXISTS "IDX_instance_ban_ip_address" ON "instance_bans" ("ip_address") ',
    'CREATE INDEX IF NOT EXISTS "IDX_instance_ban_user_id" ON "instance_bans" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_invites_channel_id" ON "invites" ("channel_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_invites_guild_id" ON "invites" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_members_guild_id" ON "members" ("guild_id") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_oauth2_token_access_token_hash" ON "oauth2_tokens" ("access_token_hash") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_oauth2_token_code_hash" ON "oauth2_tokens" ("code_hash") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "IDX_oauth2_token_refresh_token_hash" ON "oauth2_tokens" ("refresh_token_hash") ',
    'CREATE INDEX IF NOT EXISTS "IDX_oauth2_token_user_application" ON "oauth2_tokens" ("user_id", "application_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_push_devices_user_id" ON "push_devices" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_rate_limits_expires_at" ON "rate_limits" ("expires_at") ',
    'CREATE INDEX IF NOT EXISTS "IDX_read_states_user_id" ON "read_states" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_recipients_channel_id" ON "recipients" ("channel_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_recipients_user_id" ON "recipients" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_relationships_to_id" ON "relationships" ("to_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_reports_reported_user_id" ON "reports" ("reported_user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_reports_status_created_at" ON "reports" ("status", "created_at") ',
    'CREATE INDEX IF NOT EXISTS "IDX_roles_guild_id" ON "roles" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_scheduled_message_due" ON "scheduled_messages" ("state", "send_at") ',
    'CREATE INDEX IF NOT EXISTS "IDX_scheduled_message_user_id" ON "scheduled_messages" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_stage_instances_guild_id" ON "stage_instances" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_status_incident_status" ON "status_incidents" ("status") ',
    'CREATE INDEX IF NOT EXISTS "IDX_stickers_guild_id" ON "stickers" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_store_items_pack_id" ON "store_items" ("pack_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_tags_channel_id" ON "tags" ("channel_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_thread_members_member_idx" ON "thread_members" ("member_idx") ',
    'CREATE INDEX IF NOT EXISTS "IDX_thread_members_user_id" ON "thread_members" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_user_violation_user_id" ON "user_violations" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_voice_states_channel_id" ON "voice_states" ("channel_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_voice_states_guild_id" ON "voice_states" ("guild_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_voice_states_user_id" ON "voice_states" ("user_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_webhooks_channel_id" ON "webhooks" ("channel_id") ',
    'CREATE INDEX IF NOT EXISTS "IDX_webhooks_guild_id" ON "webhooks" ("guild_id") ',
    'CREATE UNIQUE INDEX IF NOT EXISTS "UQ_push_devices_provider_token" ON "push_devices" ("provider", "token") ',
    "CREATE TABLE IF NOT EXISTS guild_insights_daily (guild_id bigint NOT NULL, day date NOT NULL, metric varchar NOT NULL, key varchar NOT NULL DEFAULT '', value bigint NOT NULL DEFAULT 0, PRIMARY KEY(guild_id,day,metric,key), FOREIGN KEY(guild_id) REFERENCES guilds(id) ON DELETE CASCADE)",
    "CREATE TABLE IF NOT EXISTS guild_insights_activity (guild_id bigint NOT NULL, day date NOT NULL, channel_id bigint NOT NULL, user_id bigint NOT NULL, kinds integer NOT NULL DEFAULT 0, PRIMARY KEY(guild_id,day,channel_id,user_id), FOREIGN KEY(guild_id) REFERENCES guilds(id) ON DELETE CASCADE)",
    "CREATE TABLE IF NOT EXISTS guild_insights_rollups (day date PRIMARY KEY NOT NULL, rolled_up_at datetime NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')))",
    "CREATE TABLE IF NOT EXISTS mfa_ticket_attempts (ticket_hash varchar(64) PRIMARY KEY NOT NULL, attempts integer NOT NULL CHECK(attempts BETWEEN 1 AND 5), consumed boolean NOT NULL DEFAULT false, expires_at datetime NOT NULL)",
    "CREATE TABLE IF NOT EXISTS store_item_deletions (sku_id varchar(20) PRIMARY KEY NOT NULL, deleted_at datetime NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')))",
    "CREATE TABLE IF NOT EXISTS storage_runtime_objects (namespace varchar(128) NOT NULL, path varchar(2048) NOT NULL, principal varchar(128) NOT NULL, category varchar NOT NULL, budget_principal varchar(128) NOT NULL, bytes bigint NOT NULL DEFAULT 0 CHECK(bytes>=0), reserved_bytes bigint NOT NULL DEFAULT 0 CHECK(reserved_bytes>=0), pending boolean NOT NULL DEFAULT false, operation_generation varchar NOT NULL DEFAULT '', PRIMARY KEY(namespace,path))",
    "CREATE INDEX IF NOT EXISTS storage_runtime_principal ON storage_runtime_objects(namespace,principal)",
    "CREATE INDEX IF NOT EXISTS IDX_guild_insights_activity_day ON guild_insights_activity(day)",
    "CREATE INDEX IF NOT EXISTS IDX_mfa_ticket_attempts_expiry ON mfa_ticket_attempts(expires_at)",
    "CREATE INDEX IF NOT EXISTS IDX_messages_slowmode_channel_author_timestamp ON messages(channel_id,author_id,timestamp DESC) WHERE webhook_id IS NULL",
    "CREATE INDEX IF NOT EXISTS IDX_users_admin_created_id ON users(created_at DESC,id DESC)",
    "CREATE TRIGGER IF NOT EXISTS TR_users_store_selections_insert AFTER INSERT ON \"users\"\nWHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM json_each(CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN NEW.profile_collectibles ELSE '[]' END) entry JOIN store_item_deletions d ON d.sku_id = entry.value ->> 'sku_id')\nBEGIN UPDATE \"users\" SET\navatar_decoration_data = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id') THEN NULL ELSE NEW.avatar_decoration_data END,\ncollectibles = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id') THEN json_set(NEW.collectibles,'$.nameplate',NULL) ELSE NEW.collectibles END,\nprofile_collectibles = CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN (SELECT json_group_array(json(value)) FROM json_each(NEW.profile_collectibles) WHERE NOT EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = value ->> 'sku_id')) ELSE NEW.profile_collectibles END\nWHERE \"id\" = NEW.\"id\"; END",
    "CREATE TRIGGER IF NOT EXISTS TR_users_store_selections_update AFTER UPDATE OF avatar_decoration_data,collectibles,profile_collectibles ON \"users\"\nWHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM json_each(CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN NEW.profile_collectibles ELSE '[]' END) entry JOIN store_item_deletions d ON d.sku_id = entry.value ->> 'sku_id')\nBEGIN UPDATE \"users\" SET\navatar_decoration_data = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id') THEN NULL ELSE NEW.avatar_decoration_data END,\ncollectibles = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id') THEN json_set(NEW.collectibles,'$.nameplate',NULL) ELSE NEW.collectibles END,\nprofile_collectibles = CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN (SELECT json_group_array(json(value)) FROM json_each(NEW.profile_collectibles) WHERE NOT EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = value ->> 'sku_id')) ELSE NEW.profile_collectibles END\nWHERE \"id\" = NEW.\"id\"; END",
    "CREATE TRIGGER IF NOT EXISTS TR_members_store_selections_insert AFTER INSERT ON \"members\"\nWHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM json_each(CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN NEW.profile_collectibles ELSE '[]' END) entry JOIN store_item_deletions d ON d.sku_id = entry.value ->> 'sku_id')\nBEGIN UPDATE \"members\" SET\navatar_decoration_data = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id') THEN NULL ELSE NEW.avatar_decoration_data END,\ncollectibles = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id') THEN json_set(NEW.collectibles,'$.nameplate',NULL) ELSE NEW.collectibles END,\nprofile_collectibles = CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN (SELECT json_group_array(json(value)) FROM json_each(NEW.profile_collectibles) WHERE NOT EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = value ->> 'sku_id')) ELSE NEW.profile_collectibles END\nWHERE \"index\" = NEW.\"index\"; END",
    "CREATE TRIGGER IF NOT EXISTS TR_members_store_selections_update AFTER UPDATE OF avatar_decoration_data,collectibles,profile_collectibles ON \"members\"\nWHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id')\nOR EXISTS(SELECT 1 FROM json_each(CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN NEW.profile_collectibles ELSE '[]' END) entry JOIN store_item_deletions d ON d.sku_id = entry.value ->> 'sku_id')\nBEGIN UPDATE \"members\" SET\navatar_decoration_data = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.avatar_decoration_data ->> 'sku_id') THEN NULL ELSE NEW.avatar_decoration_data END,\ncollectibles = CASE WHEN EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = NEW.collectibles -> 'nameplate' ->> 'sku_id') THEN json_set(NEW.collectibles,'$.nameplate',NULL) ELSE NEW.collectibles END,\nprofile_collectibles = CASE WHEN json_type(NEW.profile_collectibles) = 'array' THEN (SELECT json_group_array(json(value)) FROM json_each(NEW.profile_collectibles) WHERE NOT EXISTS(SELECT 1 FROM store_item_deletions WHERE sku_id = value ->> 'sku_id')) ELSE NEW.profile_collectibles END\nWHERE \"index\" = NEW.\"index\"; END",
    "CREATE TABLE IF NOT EXISTS message_purges (channel_id bigint PRIMARY KEY NOT NULL, created_at datetime NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')))",
    "CREATE TABLE IF NOT EXISTS guild_entity_deletes (guild_id bigint NOT NULL, entity_type smallint NOT NULL, entity_id bigint NOT NULL, version bigint NOT NULL)",
    "CREATE INDEX IF NOT EXISTS IDX_guild_entity_deletes_guild_version ON guild_entity_deletes(guild_id,version)",
    "CREATE TRIGGER IF NOT EXISTS TRG_channels_queue_message_purge AFTER DELETE ON channels BEGIN INSERT INTO message_purges(channel_id) VALUES (OLD.id) ON CONFLICT DO NOTHING; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_channels_version_insert AFTER INSERT ON channels BEGIN UPDATE channels SET version = CAST((julianday('now') - 2440587.5) * 86400000 AS bigint) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_channels_version_update AFTER UPDATE ON channels WHEN NEW.version <= OLD.version BEGIN UPDATE channels SET version = MAX(CAST((julianday('now') - 2440587.5) * 86400000 AS bigint), OLD.version + 1) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_channels_record_delete AFTER DELETE ON channels WHEN OLD.guild_id IS NOT NULL AND OLD.type NOT IN (10,11,12) AND EXISTS (SELECT 1 FROM guilds WHERE id=OLD.guild_id) BEGIN INSERT INTO guild_entity_deletes VALUES(OLD.guild_id,0,OLD.id,CAST((julianday('now') - 2440587.5) * 86400000 AS bigint)); END",
    "CREATE TRIGGER IF NOT EXISTS TRG_roles_version_insert AFTER INSERT ON roles BEGIN UPDATE roles SET version = CAST((julianday('now') - 2440587.5) * 86400000 AS bigint) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_roles_version_update AFTER UPDATE ON roles WHEN NEW.version <= OLD.version BEGIN UPDATE roles SET version = MAX(CAST((julianday('now') - 2440587.5) * 86400000 AS bigint), OLD.version + 1) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_roles_record_delete AFTER DELETE ON roles WHEN OLD.guild_id IS NOT NULL AND EXISTS (SELECT 1 FROM guilds WHERE id=OLD.guild_id) BEGIN INSERT INTO guild_entity_deletes VALUES(OLD.guild_id,1,OLD.id,CAST((julianday('now') - 2440587.5) * 86400000 AS bigint)); END",
    "CREATE TRIGGER IF NOT EXISTS TRG_emojis_version_insert AFTER INSERT ON emojis BEGIN UPDATE emojis SET version = CAST((julianday('now') - 2440587.5) * 86400000 AS bigint) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_emojis_version_update AFTER UPDATE ON emojis WHEN NEW.version <= OLD.version BEGIN UPDATE emojis SET version = MAX(CAST((julianday('now') - 2440587.5) * 86400000 AS bigint), OLD.version + 1) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_emojis_record_delete AFTER DELETE ON emojis WHEN OLD.guild_id IS NOT NULL AND EXISTS (SELECT 1 FROM guilds WHERE id=OLD.guild_id) BEGIN INSERT INTO guild_entity_deletes VALUES(OLD.guild_id,2,OLD.id,CAST((julianday('now') - 2440587.5) * 86400000 AS bigint)); END",
    "CREATE TRIGGER IF NOT EXISTS TRG_stickers_version_insert AFTER INSERT ON stickers BEGIN UPDATE stickers SET version = CAST((julianday('now') - 2440587.5) * 86400000 AS bigint) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_stickers_version_update AFTER UPDATE ON stickers WHEN NEW.version <= OLD.version BEGIN UPDATE stickers SET version = MAX(CAST((julianday('now') - 2440587.5) * 86400000 AS bigint), OLD.version + 1) WHERE id = NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_stickers_record_delete AFTER DELETE ON stickers WHEN OLD.guild_id IS NOT NULL AND EXISTS (SELECT 1 FROM guilds WHERE id=OLD.guild_id) BEGIN INSERT INTO guild_entity_deletes VALUES(OLD.guild_id,3,OLD.id,CAST((julianday('now') - 2440587.5) * 86400000 AS bigint)); END",
    "CREATE TRIGGER IF NOT EXISTS TRG_guilds_channels_version_insert AFTER INSERT ON guilds BEGIN UPDATE guilds SET channels_version=CAST((julianday('now') - 2440587.5) * 86400000 AS bigint) WHERE id=NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_guilds_channels_version_update AFTER UPDATE OF channel_ordering ON guilds WHEN NEW.channel_ordering IS DISTINCT FROM OLD.channel_ordering BEGIN UPDATE guilds SET channels_version=MAX(CAST((julianday('now') - 2440587.5) * 86400000 AS bigint), OLD.channels_version+1) WHERE id=NEW.id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_tags_channel_version_insert AFTER INSERT ON tags BEGIN UPDATE channels SET version=0 WHERE id=NEW.channel_id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_tags_channel_version_update AFTER UPDATE ON tags BEGIN UPDATE channels SET version=0 WHERE id=NEW.channel_id; END",
    "CREATE TRIGGER IF NOT EXISTS TRG_tags_channel_version_delete AFTER DELETE ON tags BEGIN UPDATE channels SET version=0 WHERE id=OLD.channel_id; END",
];
const badges = [
    ["5e74e9b61934fc1f67c65515d1f7e60d", "Staff"],
    ["3f9748e53446a137a052f3454e2de41e", "Partnered Server Owner"],
    ["fee1624003e2fee35cb398e125dc479b", "Moderator Programs Alumni"],
    ["bf01d1073931f921909045f3a39fd264", "HypeSquad Events"],
    ["8a88d63823d8a71cd5e390baa45efa02", "HypeSquad Bravery"],
    ["011940fd013da3f7fb926e4a1cd2e618", "HypeSquad Brilliance"],
    ["3aa41de486fa12454c3761e8e223442e", "HypeSquad Balance"],
    ["2717692c7dca7289b35297368a940dd0", "Bug Hunter"],
    ["848f79194d4be5ff5f81505cbd0ce1e6", "Gold Bug Hunter"],
    ["6df5892e0f35b051f8b61eace34f4967", "Early Verified Bot Developer"],
    ["6bdc42827a38498929a4920da12695d9", "Active Developer"],
    ["7060786766c9c840eb3019e725d2b358", "Early Supporter"],
];

const categories = [
    {
        id: 0,
        name: "General",
        localizations: {},
        is_primary: true,
        icon: null,
    },
    {
        id: 1,
        name: "Gaming",
        localizations: {
            de: "Gaming",
            fr: "Gaming",
            ru: "Игры",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 2,
        name: "Music",
        localizations: {
            de: "Musik",
            fr: "Musique",
            ru: "Музыка",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 3,
        name: "Entertainment",
        localizations: {
            de: "Unterhaltung",
            fr: "Divertissements",
            ru: "Развлечение",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 4,
        name: "Creative Arts",
        localizations: {
            de: "Kreative Künste",
            fr: "Arts créatifs",
            ru: "Искусство",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 5,
        name: "Science & Tech",
        localizations: {
            de: "Wissenschaft & Technik",
            fr: "Science et technologie",
            ru: "Наука и техника",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 6,
        name: "Education",
        localizations: {
            de: "Lernen",
            fr: "Éducation",
            ru: "Образование",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 7,
        name: "Sports",
        localizations: {
            de: "Sport",
            fr: "Sports",
            ru: "Спорт",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 8,
        name: "Fashion & Beauty",
        localizations: {
            de: "Fashion & Beauty",
            fr: "Mode et beauté",
            ru: "Мода и красота",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 9,
        name: "Relationships & Identity",
        localizations: {
            de: "Beziehungen & Identität",
            fr: "Relations et identité",
            ru: "Отношения и самоидентификация",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 10,
        name: "Travel & Food",
        localizations: {
            de: "Reisen & Essen",
            fr: "Voyage et nourriture",
            ru: "Путешествия и еда",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 11,
        name: "Fitness & Health",
        localizations: {
            de: "Fitness & Gesundheit",
            fr: "Fitness et santé",
            ru: "Фитнес и здоровье",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 12,
        name: "Finance",
        localizations: {
            de: "Finanzen",
            fr: "Finance",
            ru: "Финансы",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 13,
        name: "Other",
        localizations: {
            de: "Sonstiges",
            fr: "Autre",
            ru: "Другое",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 14,
        name: "General Chatting",
        localizations: {
            de: "Allgemeine Chats",
            fr: "Discussion générale",
            ru: "Общение",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 15,
        name: "Esports",
        localizations: {
            de: "E-Sports",
            fr: "eSport",
            ru: "Киберспорт",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 16,
        name: "Anime & Manga",
        localizations: {
            de: "Anime & Manga",
            fr: "Animés et mangas",
            ru: "Аниме и манга",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 17,
        name: "Movies & TV",
        localizations: {
            de: "Film & TV",
            fr: "Films et TV",
            ru: "Кино и телевидение",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 18,
        name: "Books",
        localizations: {
            de: "Bücher",
            fr: "Livres",
            ru: "Книги",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 19,
        name: "Art",
        localizations: {
            de: "Kunst",
            fr: "Art",
            ru: "Творчество",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 20,
        name: "Writing",
        localizations: {
            de: "Schreiben",
            fr: "Écriture",
            ru: "Литература",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 21,
        name: "Crafts, DIY, & Making",
        localizations: {
            de: "Basteln & Handwerk",
            fr: "Travaux manuels, bricolage et artisanat",
            ru: "Хобби, рукоделие",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 22,
        name: "Programming",
        localizations: {
            de: "Programmieren",
            fr: "Programmation",
            ru: "Программирование",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 23,
        name: "Podcasts",
        localizations: {
            de: "Podcasts",
            fr: "Podcasts",
            ru: "Подкасты",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 24,
        name: "Tabletop Games",
        localizations: {
            de: "Tabletop-Spiele",
            fr: "Jeux de société",
            ru: "Настольные игры",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 25,
        name: "Memes",
        localizations: {
            de: "Memes",
            fr: "Memes",
            ru: "Мемы",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 26,
        name: "News & Current Events",
        localizations: {
            de: "Nachrichten & Zeitgeschehen",
            fr: "Actualité",
            ru: "Новости и текущие события",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 27,
        name: "Cryptocurrency",
        localizations: {
            de: "Kryptowährung",
            fr: "Cryptomonnaie",
            ru: "Криптовалюта",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 28,
        name: "Investing",
        localizations: {
            de: "Geldanlage",
            fr: "Investissements",
            ru: "Инвестиции",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 29,
        name: "Studying & Teaching",
        localizations: {
            de: "Lernen & Lehren",
            fr: "Études et enseignement",
            ru: "Обучение",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 30,
        name: "LFG",
        localizations: {
            de: "LFG",
            fr: "LFG",
            ru: "Поиск группы",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 31,
        name: "Customer Support",
        localizations: {
            de: "Kundensupport",
            fr: "Assistance clientèle",
            ru: "Служба поддержки",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 32,
        name: "Theorycraft",
        localizations: {
            de: "Theorycraft",
            fr: "Theorycraft",
            ru: "Теорикрафтинг",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 33,
        name: "Events",
        localizations: {
            de: "Events",
            fr: "Événements",
            ru: "Мероприятия",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 34,
        name: "Roleplay",
        localizations: {
            de: "Rollenspiele",
            fr: "Jeux de rôles",
            ru: "Ролевая игра",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 35,
        name: "Content Creator",
        localizations: {
            de: "Content Creator",
            fr: "Créateur de contenu",
            ru: "Создатель контента",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 36,
        name: "Business",
        localizations: {
            de: "Unternehmen",
            fr: "Activités commerciales",
            ru: "Бизнес",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 37,
        name: "Local Group",
        localizations: {
            de: "Lokale Gruppen",
            fr: "Groupe local",
            ru: "Местная группа",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 38,
        name: "Collaboration",
        localizations: {
            de: "Kollaboration",
            fr: "Collaboration",
            ru: "Совместная работа",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 39,
        name: "Fandom",
        localizations: {
            de: "Fan-Community",
            fr: "Communauté de fans",
            ru: "Фанатское сообщество",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 40,
        name: "Wiki & Guide",
        localizations: {
            de: "Wiki & Anleitungen",
            fr: "Wiki et guide",
            ru: "Вики и руководство",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 42,
        name: "Subreddit",
        localizations: {
            de: "Subreddit",
            fr: "Subreddit",
            ru: "Сабреддит",
        },
        is_primary: false,
        icon: null,
    },
    {
        id: 43,
        name: "Emoji",
        localizations: {
            de: "Emoji",
            fr: "Émoji",
            ru: "Эмодзи",
        },
        is_primary: true,
        icon: null,
    },
    {
        id: 44,
        name: "Comics & Cartoons",
        localizations: {},
        is_primary: false,
        icon: null,
    },
    {
        id: 45,
        name: "Mobile",
        localizations: {},
        is_primary: false,
        icon: null,
    },
    {
        id: 46,
        name: "Console",
        localizations: {},
        is_primary: false,
        icon: null,
    },
    {
        id: 47,
        name: "Charity & Nonprofit",
        localizations: {},
        is_primary: false,
        icon: null,
    },
    {
        id: 48,
        name: "Game Developer",
        localizations: {},
        is_primary: false,
        icon: null,
    },
    {
        id: 49,
        name: "Bots",
        localizations: {},
        is_primary: true,
        icon: null,
    },
];
const components = [
    {
        name: "API",
        description: "Signing in, sending messages and everything else the app asks the server for.",
        position: 0,
    },
    {
        name: "Gateway",
        description: "The live connection that delivers new messages, typing and presence.",
        position: 1,
    },
    {
        name: "Media Proxy",
        description: "Attachments, avatars, emoji and embedded images.",
        position: 2,
    },
    {
        name: "Push Notifications",
        description: null,
        position: 3,
    },
    {
        name: "Search",
        description: null,
        position: 4,
    },
    {
        name: "Voice",
        description: "Voice and video calls, screen sharing and Stage channels.",
        position: 5,
    },
];

export class InitialSqlite1791809007777 implements MigrationInterface {
    name = "InitialSqlite1791809007777";
    async up(runner: QueryRunner): Promise<void> {
        for (const statement of schema) await runner.query(statement);
        for (const category of categories)
            await runner.query("INSERT INTO categories(id, name, localizations, is_primary, icon) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO NOTHING", [
                category.id,
                category.name,
                JSON.stringify(category.localizations),
                category.is_primary,
                category.icon,
            ]);
        for (const component of components)
            await runner.query(
                "INSERT INTO status_components(id, name, description, position) SELECT $1,$2,$3,$4 WHERE NOT EXISTS (SELECT 1 FROM status_components WHERE name=$2)",
                [Snowflake.generate(), component.name, component.description, component.position],
            );
        for (const [position, [icon, description]] of badges.entries()) {
            const id = position === 0 ? "1" : String(100 + position);
            await runner.query("INSERT INTO badges(id, icon, description) SELECT $1, $2, $3 WHERE NOT EXISTS (SELECT 1 FROM badges WHERE icon=$2 OR id=$1)", [
                id,
                icon,
                description,
            ]);
        }
    }
    async down(): Promise<void> {
        throw new Error("The initial SQLite schema cannot be reverted. Restore a database backup instead.");
    }
}
